apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-server
  template:
    metadata:
      labels:
        app: httpd-server
    spec:
      containers:
        - name: httpd-server
          image: httpd
          resources:
            limits:
              memory: "128Mi" #128MB
              cpu: "200m" #200 millicpu
          ports:
            - containerPort: 80
